### ISSUE TITLE
Types are incompatible with LogRocket 1.0.6

### ISSUE THREAD

**Issue by yunyu** [LogRocket/logrocket-fuzzy-search-sanitizer#5]
When trying to use with LogRocket 1.0.6, I get:

    Argument of type '{ release: string | undefined; network: { requestSanitizer: (request: INetworkRequestResponse) => any; responseSanitizer: (reponse: INetworkRequestResponse) => any; }; }' is not assignable to parameter of type 'IOptions'.

**Comment by P4sca1** [comment]
@paambaati In the source code the interface is defined like this:
```ts
interface INetworkRequestResponse {
  body?: any; // POJO or a JSON stringify equalivant
  method: string;
  headers: object;
}
```

but in the latest npm version, it is defined like this, which leads to typescript errors:
```ts
interface INetworkRequestResponse {
    body: any;
    method: string;
    headers: object;
}
```

**Comment by paambaati** [comment]
It is up to the maintainers to publish a release. @pkriete Would you mind publishing a new release with the TypeScript fix?
